apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-encounter

spec:
  # Allow job to be run in a parallel manner
  # f
  concurrencyPolicy: Allow 
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name:
            image:
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            