apiVersion: v1
kind: Pod
metadata:
  name: docker-volume
  labels:
    name: myapp
spec:
  containers:
  - name: docker
    image: docker
    command: ["sleep"]
    args: ["100000"]
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
    resources:
  volumes:
  - name: docker-socket /*mounts a file or directory from the host node's filesystem into your Pod*/ 
    hostPath:
      path: /var/run/docker.sock
      type: Socket