apiVersion: v1
kind: Pod
metadata:
  name: first-pod
spec:
  volumes:
    - name: fast0.5g
      persistentVolumeClaim:
        claimName: mypvc
  containers:
  - image: ubuntu:latest
    name: ctr1
    command:
    - /bin/bash
    - "-c"
    - "sleep 60m"
    volumeMounts:
    - mountPath: /data
      name: fast0.5g